runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: main.app